animations {
    enabled = 1
    bezier = default, 0.65, 0, 0.35, 1
    animation = windows,       1, 3, default, slide
    animation = windowsIn,     1, 3, default, slide
    animation = windowsOut,    1, 3, default, slide
    animation = windowsMove,   1, 3, default, slide
    animation = layers,        1, 3, default, slide
    animation = fade,          1, 3, default
    animation = workspaces,    1, 3, default, slide
}
